// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03.09.2024 12:16:13
const configMerger = require("C:/Users/Enes/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/plugins/**/*.{js,ts,mjs}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/composables/**/*.{js,ts,mjs}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/utils/**/*.{js,ts,mjs}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Enes/OneDrive/Masaüstü/lcvGulce/app.config.{js,ts,mjs}"] }));

module.exports = config
